name: Example Using Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    name: Demo Using Secrets
    steps:
    - name: Echo Out The Secret
      env:
        bsides_secret: ${{ secrets.demo_secret }}
      run: echo "$bsides_secret"
            echo      "${bsides_secret:0:2}+${bsides_secret:2}"
